# Generated by Django 3.2.5 on 2021-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist_key', models.CharField(max_length=20, verbose_name='Pick List Key')),
            ],
            options={
                'verbose_name': 'Pick List',
                'verbose_name_plural': 'Pick Lists',
                'db_table': 'pick_list',
            },
        ),
    ]
